[base]
env_name = robocode
checkpoint_interval = 100
[vec]
total_agents = 8192
num_buffers = 4
num_threads = 4
num_policies = 2
hist_policy_hidden_size = 512
hist_policy_num_layers = 4
hist_policy_percent = 0.0986825526

[selfplay]
enabled = 1
max_size = 100
seed = 42
opp_timeout_steps = 23164294
eval_pool_size = 8
eval_games = 0
eval_bot_games = 8192 

[env]
dr = 0
num_agents = 2
num_bots = 0
width = 800
height = 600
reward_damage = 0.00266758
reward_spot = 0
reward_melee_damage_inflicted = 0.0153914625
reward_damage_taken = -0.00830152631
reward_range_damage_inflicted = 0.0148673765
bot_policy = 6
max_ticks = 3000
bot_cl_noise = 1
bot_cl_decay = 0.0126647
hist_cl_decay = 0
hist_cl_noise = 0

[policy]
hidden_size = 512
num_layers = 4

[train]
gpus = 1
total_timesteps = 1.04093504e+09
learning_rate = 0.00203742459
anneal_lr = 1
min_lr_ratio = 0
gamma = 0.997819901
gae_lambda = 0.744058013
replay_ratio = 1.46916461
clip_coef = 0.162855715
vf_coef = 2.80316305
vf_clip_coef = 0.240199268
max_grad_norm = 1.5
ent_coef = 9.99999975e-06
anneal_ent_coef = 0
min_ent_coef_ratio = 0.1
momentum = 0.893604636
minibatch_size = 4096
horizon = 32
vtrace = 0
vtrace_rho_clip = 1
vtrace_c_clip = 1
verb_eps = 0
verb_eps_anneal_start = 0.4
verb_eps_anneal_end = 1

[sweep.train.total_timesteps]
distribution = log_normal
min = 2e8
max = 3e9
mean = 5e8
scale = auto

[sweep.vec.hist_policy_percent]
distribution = uniform
min = 0.05
max = 1.0
mean = 0.25
scale = auto

[sweep.selfplay.opp_timeout_steps]
distribution = log_normal
min = 1e7
max = 1e9
mean = 1e8
scale = auto

[sweep.policy.hidden_size]
distribution = uniform_pow2
min = 32
max = 512 
scale = auto

[sweep.policy.num_layers]
distribution = uniform
min = 1
max = 4
scale = auto

[sweep.env.dr]
distribution = uniform
min = 0.0
max = 0.6
mean = 0.3
scale = auto

[sweep.env.reward_melee_damage_inflicted]
distribution = uniform
min = 0.0
max = 0.02
mean = 0.005
scale = auto

[sweep.env.reward_range_damage_inflicted]
distribution = uniform
min = 0.0
max = 0.02
mean = 0.005
scale = auto

[sweep.env.reward_damage_taken]
distribution = uniform
min = -0.02
max = 0.0
mean = -0.005
scale = auto

#[sweep.env.bot_cl_noise]
#distribution = uniform
#max = 1.0
#min = 0.5
#mean = 0.8
#scale = auto

#[sweep.env.bot_cl_decay]
#distribution = uniform
#max = 0.25
#min = 0.01
#mean = 0.05
#scale = auto
